[package]
name = "iri-rs"
version = "0.1.0"
authors = ["Abry Rath <abry.rath@union.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.2"
